[package]
name = "sipral-nat"
description = "STUN client, TURN client and ICE."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
sipral-core.workspace = true

[lints]
workspace = true
