; SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Sipral-Commercial
; Copyright (c) 2026 Tiberiu Balasea

[lab]
exten => 9000,1,Answer()
 same => n,Playtones(ring)
 same => n,Wait(60)
 same => n,Hangup()
