[package]
name = "sipral-io-coreaudio"
description = "Audio device I/O for macOS and iOS."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
sipral-io-common = { path = "../sipral-io-common", version = "1.1.0" }

[lints.rust]
unsafe_code = "allow"
missing_docs = "warn"
unreachable_pub = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
doc_markdown = "allow"
assert_is_empty = "allow"
chunks_exact_to_as_chunks = "allow"
panic = "warn"
unwrap_used = "warn"
expect_used = "warn"
indexing_slicing = "deny"
