// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Sipral-Commercial
// Copyright (c) 2026 Tiberiu Balasea

//! Answering a connectivity check: the STUN server half every ICE agent has,
//! lite or full (RFC 8445 §7.3).
//!
//! Both roles authenticate a request the same way, resolve a role conflict by
//! the same arithmetic and sign what they send back under the same key, so
//! those steps live here once. What an agent does with a request it accepted
//! — nothing much for a lite agent, a triggered check for a full one — stays
//! with the agent.

use std::net::SocketAddr;

use super::agent::Role;
use crate::stun::{
    AttributeType, BuildError, Class, Integrity, Message, MessageBuilder, Method, error_code,
};

/// What the checks every agent applies made of a datagram.
pub(super) enum Verdict<'m> {
    /// Not a request this agent answers: the wrong class or method, or a
    /// FINGERPRINT that does not check out, which "MUST be used for
    /// connectivity checks" (RFC 8445 §7.2.4) and so is worth no reply.
    Ignore,
    /// Refused before authentication was settled; send this back, unsigned,
    /// and do nothing else.
    Refuse(Vec<u8>),
    /// Authenticated with this agent's short-term credential.
    Accept(Accepted<'m>),
}

/// A request that passed.
pub(super) struct Accepted<'m> {
    /// Whether it was signed with MESSAGE-INTEGRITY-SHA256, which the
    /// response then uses too.
    pub(super) sha256: bool,
    /// The second half of USERNAME: the fragment the peer generated, which
    /// is how a full agent finds the password for a triggered check
    /// (RFC 8445 §7.3.1.4).
    pub(super) remote_ufrag: &'m [u8],
}

/// Apply RFC 8489 §9.1.3's checks, in the order it gives them, to a request
/// that has to carry this agent's short-term credential.
pub(super) fn authenticate<'m>(
    message: &Message<'m>,
    local_ufrag: &[u8],
    local_pwd: &[u8],
) -> Verdict<'m> {
    if message.class() != Class::Request || message.method() != Method::BINDING {
        return Verdict::Ignore;
    }
    if message.verify_fingerprint() == Integrity::Invalid {
        return Verdict::Ignore;
    }
    if let Err(unknown) = message.check_comprehension() {
        return refuse(error_unsigned(
            message,
            error_code::UNKNOWN_ATTRIBUTE,
            b"unknown attribute",
            |builder| builder.add_unknown_attributes(unknown.types()),
        ));
    }

    let username = message.username();
    if username.is_none() && !message.has_integrity() {
        return refuse(error_unsigned(
            message,
            error_code::BAD_REQUEST,
            b"missing credentials",
            |_| Ok(()),
        ));
    }
    let Some(username) = username else {
        return refuse(error_unsigned(
            message,
            error_code::UNAUTHENTICATED,
            b"missing username",
            |_| Ok(()),
        ));
    };
    let Some(remote_ufrag) = remote_ufrag(username, local_ufrag) else {
        return refuse(error_unsigned(
            message,
            error_code::UNAUTHENTICATED,
            b"unknown username",
            |_| Ok(()),
        ));
    };

    let sha256 = message
        .find(AttributeType::MESSAGE_INTEGRITY_SHA256)
        .is_some();
    let authentic = if sha256 {
        message.verify_integrity_sha256(local_pwd) == Integrity::Valid
    } else {
        message.verify_integrity(local_pwd) == Integrity::Valid
    };
    if !authentic {
        return refuse(error_unsigned(
            message,
            error_code::UNAUTHENTICATED,
            b"integrity check failed",
            |_| Ok(()),
        ));
    }
    Verdict::Accept(Accepted {
        sha256,
        remote_ufrag,
    })
}

fn refuse<'m>(reply: Option<Vec<u8>>) -> Verdict<'m> {
    reply.map_or(Verdict::Ignore, Verdict::Refuse)
}

/// The peer's fragment, when USERNAME's first colon-separated value is this
/// agent's own (RFC 8445 §7.3): "the first value is equal to the username
/// fragment generated by the agent".
pub(super) fn remote_ufrag<'m>(username: &'m [u8], local_ufrag: &[u8]) -> Option<&'m [u8]> {
    username.strip_prefix(local_ufrag)?.strip_prefix(b":")
}

/// RFC 8445 §7.3.1.1's role-conflict arithmetic, applied to one request.
///
/// `true` means the request loses and gets a 487; the role has already been
/// flipped in the other case, if that is what the tiebreaker called for. A
/// request naming the role this agent does not hold — ICE-CONTROLLING to a
/// controlled agent, or the reverse — is no conflict and changes nothing.
///
/// `lite` is whether the agent answering is a lite one, and for a lite agent
/// neither half of the arithmetic is a real conflict. A Binding request only
/// ever reaches a lite agent from a full peer — two lite agents exchange no
/// checks (§6.1.1) — and §6.1.1 makes "one full, one lite" the full agent's
/// controlling role unconditionally. So an ICE-CONTROLLED request naming a
/// lite agent's controlled role is always answered with a 487 that keeps
/// that role, and an ICE-CONTROLLING request reaching a lite agent that
/// started controlling — because the description it read said the peer was
/// lite too — always moves it to controlled and is answered, whatever the
/// tiebreaker says: the peer that sent it is the one doing the checks and
/// the nominating, and a lite agent that kept a role it can never act on,
/// sending no checks and nominating nothing, would leave the call with no
/// path about half the time. A full agent passes `false`: either side of a
/// full-full conflict is the real ambiguity the arithmetic is there to
/// settle.
pub(super) fn resolve_role(
    role: &mut Role,
    tiebreaker: u64,
    message: &Message<'_>,
    lite: bool,
) -> bool {
    if let Some(theirs) = message.ice_controlling() {
        if *role != Role::Controlling {
            return false;
        }
        if !lite && tiebreaker >= theirs {
            return true;
        }
        *role = Role::Controlled;
    } else if let Some(theirs) = message.ice_controlled() {
        if *role != Role::Controlled {
            return false;
        }
        if !lite && tiebreaker >= theirs {
            *role = Role::Controlling;
        } else {
            return true;
        }
    }
    false
}

/// A success response carrying the address the request came from, signed the
/// way the request was.
pub(super) fn success(
    request: &Message<'_>,
    mapped: SocketAddr,
    key: &[u8],
    sha256: bool,
) -> Option<Vec<u8>> {
    let mut builder =
        MessageBuilder::new(Class::Success, Method::BINDING, request.transaction_id());
    builder
        .add_xor_address(AttributeType::XOR_MAPPED_ADDRESS, mapped)
        .ok()?;
    sign(&mut builder, key, sha256).ok()?;
    builder.add_fingerprint().ok()?;
    Some(builder.finish())
}

/// An error response to a request that has been authenticated, which may
/// therefore be signed: "Any response generated by a server to a request that
/// contains a MESSAGE-INTEGRITY... attribute MUST include" one (RFC 8489
/// §9.1.3).
pub(super) fn error_signed(
    request: &Message<'_>,
    code: u16,
    reason: &[u8],
    key: &[u8],
    sha256: bool,
) -> Option<Vec<u8>> {
    let mut builder = MessageBuilder::new(Class::Error, Method::BINDING, request.transaction_id());
    builder.add_error_code(code, reason).ok()?;
    sign(&mut builder, key, sha256).ok()?;
    builder.add_fingerprint().ok()?;
    Some(builder.finish())
}

/// An error response built before authentication has been decided, which RFC
/// 8489 §9.1.3 forbids signing: "the server cannot determine the shared secret
/// necessary". `extra` adds whatever the error needs beyond ERROR-CODE, such
/// as UNKNOWN-ATTRIBUTES on a 420.
pub(super) fn error_unsigned(
    request: &Message<'_>,
    code: u16,
    reason: &[u8],
    extra: impl FnOnce(&mut MessageBuilder) -> Result<(), BuildError>,
) -> Option<Vec<u8>> {
    let mut builder = MessageBuilder::new(Class::Error, Method::BINDING, request.transaction_id());
    builder.add_error_code(code, reason).ok()?;
    extra(&mut builder).ok()?;
    builder.add_fingerprint().ok()?;
    Some(builder.finish())
}

fn sign(builder: &mut MessageBuilder, key: &[u8], sha256: bool) -> Result<(), BuildError> {
    if sha256 {
        builder.add_message_integrity_sha256(key)
    } else {
        builder.add_message_integrity(key)
    }
}
