// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Sipral-Commercial
// Copyright (c) 2026 Sytek
//
// Sipral for Node.js: the idiomatic layer over `sipral_abi.ts`, which
// tools/abi-gen prints and nothing here edits. A stack on UDP, TCP or TLS,
// accounts with their registration, subscriptions, presence and messages,
// calls with their media, local conferences, the device-mode audio engine,
// and the stack's events as an EventEmitter and an async iterator.

export { Account, type AccountEvents, type PinnedCertificate, type PushEcho, type SubscribeOptions } from './account.js';
export { Audio, type AudioDevice, type AudioInfo } from './audio.js';
export { Call, type CallEvents, type ConsentToneOptions, type HeaderFields, type ProgressOptions } from './call.js';
export {
  type ConferenceRecordingOptions,
  LocalConference,
  type LocalConferenceInfo,
  type LocalConferenceMember,
  type LocalConferenceOptions,
} from './conference.js';
export { type EventFields, type MediaStatistics, StackEvent } from './events.js';
export { SipralError } from './internal.js';
export {
  type Capabilities,
  type CodecInfo,
  abiCheck,
  abiVersion,
  advertisedAddress,
  capabilities,
  codecName,
  codecs,
  eventKindName,
  features,
  messageHeaderElements,
  messageHeaders,
  statusName,
  structSize,
  versionedCount,
} from './library.js';
export {
  type CodecCandidate,
  Media,
  type MediaInfo,
  type PathCandidate,
  type ProcessorFrame,
  type Protection,
  type RecordingOptions,
} from './media.js';
export {
  SIPRAL_FEATURE_AUDIO_DEVICE,
  SIPRAL_SCREEN_ACCEPT,
  Sipral,
  SipralActivity,
  SipralAmdReason,
  SipralAmdVerdict,
  SipralAnswerMode,
  SipralArrival,
  SipralAttestation,
  SipralCandidateKind,
  SipralCodecOutcome,
  SipralConferenceText,
  SipralDialogText,
  SipralDigitSource,
  SipralDirection,
  SipralMediaFault,
  SipralMediaKind,
  SipralNatKind,
  SipralNatMapping,
  SipralNatRelay,
  SipralNetworkProbe,
  SipralPathKind,
  SipralPathOutcome,
  SipralPlayback,
  SipralRecoveryFailure,
  SipralRecoveryOutcome,
  SipralRecoveryRung,
  SipralRingSource,
  SipralRtcp,
  SipralServerReach,
  SipralStunServerState,
  SipralSubscriptionEnd,
  SipralToggle,
  SipralTurnStream,
  SipralAudio,
  SipralAudioActivation,
  SipralAudioChange,
  SipralAudioDirection,
  SipralAudioOrigin,
  SipralAudioRole,
  SipralBasic,
  SipralCallEndReason,
  SipralCallState,
  SipralChallengeRefusal,
  SipralCodec,
  SipralConferenceUpdate,
  SipralDeparture,
  SipralDialogDirection,
  SipralDialogEnded,
  SipralDialogPhase,
  SipralDnsAnswer,
  SipralDnsRecordType,
  SipralDtmf,
  SipralDtmfDetection,
  SipralEndpointStatus,
  SipralEventKind,
  SipralHeldAudio,
  SipralIce,
  SipralIdentityText,
  SipralKeyExchange,
  SipralLink,
  SipralLoadError,
  SipralLocalConferenceChange,
  SipralLocateFailure,
  SipralLogLevel,
  SipralNat,
  SipralNetworkVerdict,
  SipralPresenceKind,
  SipralProgressKind,
  SipralProgressTone,
  SipralPublicationState,
  SipralPublishFailure,
  SipralRecordingFormat,
  SipralRecordingLayout,
  SipralRecovery,
  SipralRegistrationFailure,
  SipralRegistrationState,
  SipralSessionTimer,
  SipralSrtp,
  SipralSrtpSuite,
  SipralStatus,
  SipralStirVerification,
  SipralSubscriptionState,
  SipralTlsFailure,
  SipralTokenError,
  SipralToneRegion,
  SipralTransport,
  SipralTransportError,
  SipralVerificationFailure,
  SipralVerificationOutcome,
  SipralVerificationStage,
  SipralVerstat,
} from './sipral_abi.js';
export {
  type AccountOptions,
  type CallOptions,
  INVITE_LIMIT_DEFAULT,
  INVITE_LIMIT_VOICE_AGENT,
  type InviteLimit,
  type LogLine,
  type Resolver,
  Stack,
  type StackEvents,
  type StackOptions,
  routeHost,
  systemResolver,
} from './stack.js';
export { type ConferencePicture, type Participant, Subscription, type WatchedDialog } from './subscription.js';
export { type ConnectOptions, type Refusal, TlsTrust, classify, parsePin } from './tls.js';
